# Generated by Django 3.2.3 on 2021-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tage',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
