# Generated by Django 3.2.3 on 2021-05-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_tage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tage',
            new_name='tags',
        ),
    ]
