# Generated by Django 3.2.3 on 2021-05-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_updated_at'),
        ('boards', '0003_rename_tage_board_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'comment',
            },
        ),
    ]
