# Generated by Django 3.2.3 on 2021-05-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
