# Generated by Django 3.2.3 on 2021-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=64),
        ),
    ]
