# Generated by Django 3.2.3 on 2021-05-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_comment_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='board_no',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
    ]
